# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Divyadharshini Muruganandham
description: "Hi I'm Divya, and my passion lies in utilizing Data Science and Machine Learning technology to solve intricate business challenges. With a creative and methodical approach, I strive to add tangible value to teams, businesses, and end-users alike. Continuously improving my skills and staying abreast of the latest techniques and trends, I am committed to optimizing results and delivering innovative solutions. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "United States of America, USA"
resume_url: "/docs/Divyadharshini_Muruganandham_Resume.pdf"
avatar_image: "/img/photo.jpg"

#-------------------------------
# Contact links
linkedln: https://www.linkedin.com/in/muruganandhamd/ # Add your linkedln handle
github: "https://github.com/Divyadharsh"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

