# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Maruthi Manoj Kolli
description: "Hi I'm Manoj, As a seasoned data engineer and software engineer with over 5 years of experience in Industry/Technologies, I blend deep technical expertise with a passion for solving complex data challenges. .  My portfolio focuses on interesting projects I've worked on and undertaken, with a strong emphasis on business impact. Please visit my LinkedIn page (or download my Resume) by using the link below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
#location: "Boston, USA"
resume_url: "/docs/Manoj-Kolli_Resume.pdf"
avatar_image: "/img/img.jpg"

#-------------------------------
# Contact links
linkedln: https://www.linkedin.com/in/manoj-kolli/ # Add your linkedln handle
github: "https://github.com/#"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

